baseURL = "http://localhost:1313"
languageCode = "ko-KR"
title = "ê¹€ë¨¸ì„± ë¸”ë¡œ9"
theme = "github-style"

[params]
  author = "ê¹€ë¨¸ì„±"
  description = "Description"
  github = "ê¹€ë¨¸ì„±"
  facebook = "ê¹€ë¨¸ì„±"
  twitter = "ê¹€ë¨¸ì„±"
  linkedin = "ê¹€ë¨¸ì„±"
  instagram = "ê¹€ë¨¸ì„±"
  tumblr = "ê¹€ë¨¸ì„±"
  email = "rlaajtjd0514@gmail.com"
  url = "https://rlaeotjd0514.github.io/Blog/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/favicon.ico"
  avatar = "/images/github.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Korea"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "LuvSia"
    owner = "ventusoon"
    admin = "ventusoon"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last" # Comment sorting direction, available values are "last" and "first".
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "/post"
    href = "http://localhost:1313/content/post"
  [[params.links]]
    title = "Link2"
    href = "https://meik2333.com"
    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"